baseURL = "/"
title = "REWINE NOTE"

theme = "PaperMod"
hasCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true

## Change this two to switch between different language
languageCode = "zh-cn"  # For RSS, view https://www.rssboard.org/rss-language-codes
defaultContentLanguage = "zh-hans"  # For HTML page, now support: en, zh-hans, zh-hant, ja, nl

summaryLength = 100 # Custom summary length, add <!--more--> in post file to custom split point
pagination.pagerSize = 10


# googleAnalytics = "UA-000000000-0" # Set your Google Analytics UA here

[outputs]
  home = ["HTML", "RSS", "JSON"]

[permalinks]
  post = "/:section/:contentbasename/" # Custom post links, e.g. "/:year/:month/:title/"

[params]
  author = "rewine"

  # Open Graph & Twitter Card variables
  # You can also set description and images in post front matter individually
  description = "A minimal Hugo theme with nice theme color."

  # Posts shown in homepage
  mainSections = ["post"]
  ShowToc = true
  ShowReadingTime = false
  ShowWordCount = true
  ShowCodeCopyButtons = true
  comments = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "monokai"

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Archives"
    url = "/archives/"
    weight = 2
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 3
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5
  [[menu.main]]
    name = "Friends"
    url = "/friends/"
    weight = 6
  [[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 7

  [[menu.link]]
    name = "GitHub"
    url = "https://github.com/wineee"
    weight = 1
  [[menu.link]]
    name = "Twitter"
    url = "https://twitter.com/rewineeee"
    weight = 2
  [[menu.link]]
    name = "bilibili"
    url = "https://space.bilibili.com/23192485"
    weight = 3
